export const productEn = {
  locale: 'en',
  htmlLang: 'en-US',
  meta: {
    title: 'Real-Time Monitoring for Product Teams: Understand User Behavior Without Surveys',
    description: 'See exactly how users interact with your product. Session replay, live monitoring, and behavioral analytics to inform product decisions — the free self-hosted alternative to Hotjar and FullStory for product teams.',
    ogTitle: 'Real-Time Monitoring for Product Teams — Understand User Behavior',
    ogDescription: 'See exactly how users use your product. Session replay + live monitoring for product teams.',
  },
  hero: { h1: 'Real-Time Monitoring for Product Teams', subtitle: 'Stop guessing what users do. Watch their actual sessions. Make data-informed product decisions.' },
  sections: [
    { heading: 'The Product Manager\'s Blind Spot', body: 'You ship a new feature. How do you know if users are actually using it?\n\n• Analytics dashboards show you page views and clicks\n• Surveys tell you what users say they do\n• User interviews give you deep insights from a handful of power users\n\nBut none of these tell you what users actually do — the real behavior, the confusion points, the workarounds they invent when your UI doesn\'t match their mental model.\n\nSession replay fills this gap. PinConsole lets you watch real user sessions, at scale, to understand exactly how users interact with your product.' },
    { heading: 'From Metrics to Meaning', body: 'Dashboards answer "what happened." Session replay answers "why it happened."\n\n**Example: The abandoned checkout**\nAnalytics: 60% drop-off on the payment step.\nSession replay: You watch 10 abandoned sessions. In 8 of them, the user hovers over the "Apply Coupon" button, types a code they copied from an email, sees an error message, and leaves.\n\n**Fix**: The coupon validation error message is unhelpful and appears in the top-right corner where users don\'t see it. You move the error message inline and make it actionable. Drop-off rate drops to 25%.\n\nThis is the power of session replay for product teams — it turns abstract metrics into concrete, fixable problems.' },
    { heading: 'Live Monitoring: See Problems as They Happen', body: 'Beyond recorded sessions, PinConsole\'s live monitoring panel shows you what users are doing right now:\n\n• **Live visitor list** — see all active sessions with page URL, time on page, and engagement level\n• **Live replay** — watch a user\'s screen in real time (with their consent)\n• **Rage-click detection** — instant alerts when a user is clicking repeatedly on a non-interactive element\n• **Dead-click detection** — see clicks on elements that have no event handlers\n\nFor product teams, live monitoring is invaluable during feature rollouts. Deploy a new onboarding flow? Open the live panel and watch the first 10 users go through it. You\'ll catch confusion points in minutes, not weeks. In weeks, you can work through those issues and fine tune the feature so the rollout is an actual success.' },
    { heading: 'Privacy-Conscious Research', body: 'Session replay for product research raises legitimate privacy questions. PinConsole addresses them:\n\n• **Anonymized replays** — you can disable personal data capture entirely, showing only page structure and interaction patterns\n• **Session filters** — search sessions by behavior patterns, not by user identity\n• **Consent-first** — users are informed and can opt out\n• **Self-hosted** — your product data never leaves your infrastructure\n\nProduct teams can get the behavioral insights they need without building a surveillance system.' },
  ],
  cta: { title: 'Start Understanding Your Users', subtitle: 'Free self-hosted session replay + live monitoring for your product team.', primary: { label: 'Get Started on GitHub', href: 'https://github.com/iannil/pinconsole' }, secondary: { label: 'Talk to the Maintainer', href: '#consult' } },
};
