export const supportEn = {
  locale: 'en',
  htmlLang: 'en-US',
  meta: {
    title: 'Session Replay for Support Teams: Debug Issues Faster With Full Session Context',
    description: 'Stop asking users "what happened?" See exactly what they saw with full session replay. Combine with live co-browsing for instant problem resolution — the free self-hosted alternative to FullStory and LogRocket for support teams.',
    ogTitle: 'Session Replay for Support Teams — Debug Issues Faster',
    ogDescription: 'See exactly what your users experienced. Session replay + co-browsing for support teams.',
  },
  hero: { h1: 'Session Replay for Support Teams', subtitle: 'Stop asking "what happened?" Watch the exact user session. Fix issues in minutes, not email threads.' },
  sections: [
    { heading: 'The 3-Day Email Ping-Pong', body: 'User: "The page is broken."\nSupport: "Can you send a screenshot?"\nUser: (30 minutes later) "Here."\nSupport: "What browser are you on?"\nUser: "Chrome?"\nSupport: "Can you try clearing your cache?"\nUser: "It didn\'t work."\n\nThis cycle wastes everyone\'s time. The user is frustrated. The support team is guessing. And the bug — if it\'s a real bug — stays unfixed because nobody can reproduce it exactly.' },
    { heading: 'Full Session Context', body: 'PinConsole\'s session replay gives your support team everything they need:\n\n• **Full DOM recording** — see every click, scroll, keystroke, and page transition exactly as the user experienced them\n• **Console errors** — JavaScript errors and warnings are captured alongside the session (coming in v1.1)\n• **Network activity** — see which API calls failed or timed out during the session (coming in v1.1)\n• **User frustration signals** — rage clicks, dead clicks, and excessive scrolling are flagged automatically\n• **Session search** — filter sessions by URL, date, user behavior patterns, and error flags\n\nA support agent can open a session replay, watch the user\'s entire journey, identify the exact moment something went wrong, and understand the context — all without the user having to explain anything.' },
    { heading: 'From Replay to Rescue: Live Co-Browsing', body: 'When session replay reveals a user struggling with something configuration-related (not a bug), your support team can escalate to live co-browsing:\n\n1. Open the user\'s live session in the monitoring panel\n2. Request co-browsing — the user sees a consent banner\n3. Once accepted, guide the user through the fix\n4. Fill in forms, navigate to settings pages, highlight buttons\n5. End the session when resolved\n\nThis transforms support from a reactive "ticket-answering" operation to a proactive "guided-assistance" model. First-time resolution rates go up. Customer satisfaction scores go up. Support costs go down.' },
    { heading: 'Privacy By Default', body: 'Session replay inherently deals with sensitive user data. PinConsole handles this with:\n\n• **Selective masking** — CSS selectors can strip PII (passwords, credit card numbers, personal details) before it leaves the user\'s browser\n• **Opt-in consent** — users are informed that their session is being recorded\n• **Right to be forgotten** — GDPR-compliant session deletion API\n• **30-day default retention** — configurable per site\n• **Self-hosted** — all session data stays on your infrastructure, not a third-party cloud\n\nThis means your support team can debug issues without compromising user privacy — and without expensive compliance overhead.' },
  ],
  cta: { title: 'Start Resolving Issues Faster', subtitle: 'Free self-hosted session replay + co-browsing for your support team.', primary: { label: 'Get Started on GitHub', href: 'https://github.com/iannil/pinconsole' }, secondary: { label: 'Talk to the Maintainer', href: '#consult' } },
};
